version: '3.4'
services:
  test:
    build: .
    image: upparat:local
    entrypoint: /usr/local/bin/pytest
    command: --durations=3 -s ./tests/ --log-cli-level=CRITICAL -vv
    volumes:
      # make sure to not mount over .egginfo in /app/upparat
      - ./src/upparat:/app/upparat/src/upparat:cached
      - ./tests:/app/upparat/tests/:cached
  format:
    image: jbbarth/black
    command: .
    volumes:
      - .:/code
