version: '3.4'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    working_dir: /mosquitto
    command: "/usr/sbin/mosquitto -c /mosquitto/aws-bridge.conf -v"
    volumes:
      - ./mosquitto/aws-bridge.conf:/mosquitto/aws-bridge.conf
      - ./upparat/config/cafile:/certs/cafile
      - ./upparat/config/certfile:/certs/certfile
      - ./upparat/config/keyfile:/certs/keyfile
  upparat-bridged:
    build: ../../.
    image: upparat:local
    command: --verbose --config /config/config.ini
    volumes:
      # use bridge config
      - ./upparat/config/config.bridge.ini:/config/config.ini
      - ./upparat/hooks/:/hooks/
      - ./upparat/tmp:/tmp
      # make sure to not mount over .egginfo in /app/upparat
      - ../../src/upparat:/app/upparat/src/upparat
      - ../../setup.py:/app/upparat/setup.py
      - ../../setup.cfg:/app/upparat/setup.cfg
    depends_on:
      - mosquitto
  upparat-alpn:
    build: ../../.
    image: upparat:local
    command: --verbose --config /config/config.ini
    volumes:
      # use ALPN config
      - ./upparat/config/config.alpn.ini:/config/config.ini
      - ./upparat/config/cafile:/config/cafile
      - ./upparat/config/certfile:/config/certfile
      - ./upparat/config/keyfile:/config/keyfile
      - ./upparat/hooks/:/hooks/
      - ./upparat/tmp:/tmp
      # make sure to not mount over .egginfo in /app/upparat
      - ../../src/upparat:/app/upparat/src/upparat
      - ../../setup.py:/app/upparat/setup.py
      - ../../setup.cfg:/app/upparat/setup.cfg
